services:
  rag-chatbot:
    build: .
    container_name: rag_chatbot_app
    ports:
      - "8000:8000"
      - "8501:8501"
    volumes:
      # Keeps user uploaded data & vector database persistent on their laptop
      - ./data:/app/data
      # Live code reloading (changes reflect immediately without rebuilding Docker)
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./Rag_Chatbot.py:/app/Rag_Chatbot.py
    env_file:
      - .env
    restart: unless-stopped
